###### Frontend build log:

   FROM node:lts AS builder
    
    WORKDIR /app

    COPY webui webui
     
    WORKDIR /app/webui
    
    RUN yarn run build-prod

    FROM nginx:stable

    COPY --from=builder /app/webui/dist /usr/share/nginx/html
