openapi: 3.0.0
info: 
  description: WASAText exam project Rest API
  title: WASAText
  version: 1.0.0
servers:
- url: http://localhost:3000
components:
  schemas:
    user:
      title: user
      description: "This object represent the unique name of the user (\"user\")."
      type: object
      properties:
        username:
          description: Unique name of the user
          type: string
          example: ricc
        profileImage:
          description: profile picture of the user
          type: string
          example: https://media.istockphoto.com/id/1602458519/it/foto/esplosione-di-polvere-colorata-su-sfondo-bianco.jpg?s=612x612&w=0&k=20&c=p8zsmnvNd6Nj2I0cTE8esB79X_CnjkwH4FUTp3U9_eA=
        bio:
          description: biography of the user
          type: string
          example: 18y/o italian
        firstName:
          description: the real name of the user 
          type: string
          example: roberto
        lastName:
          description: the real surname of the user
          type: string
          example: rossi
    textMessage:
      title: text message
      description: a simple text between users
      type: object
      properties:
        id: 
          description: unique identifier
          type: integer
          example: 1
        content:
          description: the text content of the message
          type: string
          example: ciao come stai
        preview: 
          description: the snippet of the text
          type: string
          example: ciao com-
        sender:
          description: the username of the user who has sent the message
          type: string
          example: ricc
        date:
          description: the date of the sent message 
          type: number
          example: 11052024
        checkmark:
          description: the graphic rappresentation of the state of the message, seen or just delivered
          type: integer
          enum: [1, 2]
          example: 1
        responseTo:
          description: if the text is a reaction to another message, here is the id of that message. zero means that it isn t a response to another message
          type: integer
          example: 0
        photoContent:
          description: the url of the photo, if its empty then this is a simple text message
          type: string
          example: https://immagine.png
        icon:
          description: the preview of the photo in icon version, the value is taken only if its a photo message
          type: string
          example: https://icon.png

    chat:
      title: chat
      description: the chat between two users
      type: object
      properties:
        id:
          description: unique identifier
          type: integer
          example: 89
        user1:
          description: the id of the fist user of the chat
          type: integer
          example: 1
        user2:
          description: the id of the second user of the chat
          type: integer
          example: 2
        textMessageList:
          description: the ids of the messages sent in this conversation
          type: array
          items:
            $ref: '#/components/schemas/textMessage'
        receiver:
          description: the id of the user who has received the message (it has to be one of the two user of the chat)
          type: integer
          example: 2
    group:
      title: group
      description: group between users
      type: object
      properties:
        id:
          description: unique identifier
          type: integer
          example: 72
        partecipant:
          description: id of the users in the group
          type: array
          items:
            $ref: '#/components/schemas/user'
        textMessageList:
          description: the ids of the messages sent in this conversation
          type: array
          items:
            $ref: '#/components/schemas/textMessage'
          
paths: